server:
  port: 13105
#spring.datasource.primary.jdbc-url=jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
#spring.datasource.primary.username=root
#spring.datasource.primary.password=IMCsoft.12345
#spring.datasource.primary.driver-class-name=com.mysql.jdbc.Driver
#
#spring.datasource.secondary.jdbc-url=jdbc:oracle:thin:@192.168.21.204:1521:nrfw
#spring.datasource.secondary.username=MSYIDAOAPP
#spring.datasource.secondary.password=ms123
#spring.datasource.secondary.driver-class-name=oracle.jdbc.driver.OracleDriver
spring:
  datasource:
    primary:
      username: ${DATASOURCE_USERNAMR:root}
      password: ${DATASOURCE_PASSWORD:IMCsoft.12345}
      jdbc-url: jdbc:mysql://${IP:127.0.0.1}:3306/cns-serve?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      #      jdbc-url: jdbc:p6spy:mysql://${DB_IP:127.0.0.1}:3306/cns-serve?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
      #      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    secondary:
      jdbc-url: jdbc:oracle:thin:@${SLW_DB_IP:192.168.21.204}:1521:nrfw
      username: ${SLW_DATASOURCE_USERNAMR:MSYIDAOAPP}
      password: ${SLW_DATASOURCE_PASSWORD:ms123}
      driver-class-name: oracle.jdbc.driver.OracleDriver
