server:
  port: 12106
spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle8iDialect
  datasource:
    username: ${SLW_DATASOURCE_USERNAMR:MSYIDAOAPP}
    password: ${SLW_DATASOURCE_PASSWORD:ms123}
  application:
    name: db
logging:
  file:
    name: ${LOG_HOME:/home/aiot/aiot-manage/log/}${spring.application.name}.log
---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@${SLW_DB_IP:192.168.21.204}:1521:nrfw
    driver-class-name: oracle.jdbc.driver.OracleDriver
